env:
  es2017: true
  node: true
extends:
  - 'eslint:recommended'
ignorePatterns:
  - /out
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  array-bracket-newline: error
  brace-style:
    - error
    - stroustrup
    - allowSingleLine: true
  comma-dangle:
    - error
    - always-multiline
  curly: error
  eqeqeq: warn
  function-paren-newline:
    - error
    - multiline-arguments
  generator-star-spacing:
    - error
    - after
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style: error
  no-mixed-operators:
    - error
    - groups:
      - - '&&'
        - '||'
  no-multiple-empty-lines:
    - error
    - max: 1
  no-sequences: error
  no-shadow: error
  no-throw-literal: error
  nonblock-statement-body-position: error
  object-curly-newline: error
  require-await: error
  semi:
    - error
    - never
overrides:
  - files:
    - 'spec/**/*.js'
    env:
      jasmine: true
  - files:
    - '**/*.ts'
    extends:
      - 'plugin:@typescript-eslint/recommended'
    rules:
      '@typescript-eslint/explicit-module-boundary-types':
        - error
        - allowArgumentsExplicitlyTypedAsAny: true
          allowedNames:
            - entityRewards
            - isActive
      '@typescript-eslint/no-non-null-assertion': off
      '@typescript-eslint/no-unused-vars': off
