name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 18, 21 ]
        include:
          - node: 20
            lint: true

    name: Build and test (node-${{ matrix.node }})

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Check linting
        if: ${{ matrix.lint }}
        run: npm run lint

      - name: Create required files
        run: echo '{}' | tee data/itemnames.json data/itemtypes.json

      - name: Compile
        run: npm run build

      - name: Run tests
        run: npm run test
